# docker-compose.yml
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9688:9688" # Map port 80 host ke port 8080 kontainer Go
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: mydatabase
      PORT: 8080
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:16-alpine # Gunakan image PostgreSQL resmi
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data # Persistent storage untuk data database
    networks:
      - app-network

volumes:
  pgdata: # Definisi volume untuk data PostgreSQL

networks:
  app-network: # Definisi network bridge kustom
    driver: bridge